"""empty message

Revision ID: 29303d4c6027
Revises: 
Create Date: 2023-11-07 10:55:44.602060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29303d4c6027'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_track',
    sa.Column('song_id', sa.String(length=200), nullable=False),
    sa.Column('song', sa.String(length=200), nullable=True),
    sa.Column('artist', sa.String(length=200), nullable=True),
    sa.Column('album', sa.String(length=200), nullable=True),
    sa.Column('release', sa.String(length=200), nullable=True),
    sa.Column('popularity', sa.String(length=200), nullable=True),
    sa.Column('preview_url', sa.String(length=200), nullable=True),
    sa.Column('image_url', sa.String(length=200), nullable=True),
    sa.Column('spotify_song', sa.String(length=200), nullable=True),
    sa.Column('spotify_artist', sa.String(length=200), nullable=True),
    sa.Column('spotify_album', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('song_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_track')
    # ### end Alembic commands ###
