"""empty message

Revision ID: 91f5d05466ec
Revises: 484aaa379aab
Create Date: 2023-11-07 11:06:17.997399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91f5d05466ec'
down_revision = '484aaa379aab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_track', schema=None) as batch_op:
        batch_op.alter_column('song_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               nullable=False)
        batch_op.alter_column('song',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               existing_nullable=True)
        batch_op.alter_column('artist',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               existing_nullable=True)
        batch_op.alter_column('album',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               existing_nullable=True)
        batch_op.alter_column('release',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               existing_nullable=True)
        batch_op.alter_column('popularity',
               existing_type=sa.BIGINT(),
               type_=sa.String(length=200),
               existing_nullable=True)
        batch_op.alter_column('preview_url',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               existing_nullable=True)
        batch_op.alter_column('spotify_song',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               existing_nullable=True)
        batch_op.alter_column('spotify_artist',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               existing_nullable=True)
        batch_op.alter_column('spotify_album',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               existing_nullable=True)
        batch_op.drop_index('ix_tb_track_index')
        batch_op.drop_column('index')
        batch_op.drop_column('images_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_track', schema=None) as batch_op:
        batch_op.add_column(sa.Column('images_url', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('index', sa.BIGINT(), nullable=True))
        batch_op.create_index('ix_tb_track_index', ['index'], unique=False)
        batch_op.alter_column('spotify_album',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('spotify_artist',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('spotify_song',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('preview_url',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('popularity',
               existing_type=sa.String(length=200),
               type_=sa.BIGINT(),
               existing_nullable=True)
        batch_op.alter_column('release',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('album',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('artist',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('song',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('song_id',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###
