"""empty message

Revision ID: c9480a07ffc8
Revises: f8689cda2d07
Create Date: 2023-11-20 19:23:53.333013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9480a07ffc8'
down_revision = 'f8689cda2d07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_artist',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('artist', sa.String(length=50), nullable=True),
    sa.Column('genres', sa.String(length=200), nullable=True),
    sa.Column('popularity', sa.Integer(), nullable=True),
    sa.Column('image_artist', sa.String(length=200), nullable=True),
    sa.Column('spotify_url', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('tb_followed_artists')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_followed_artists',
    sa.Column('id', sa.VARCHAR(length=100), nullable=False),
    sa.Column('artist', sa.VARCHAR(length=50), nullable=True),
    sa.Column('genres', sa.VARCHAR(length=200), nullable=True),
    sa.Column('popularity', sa.INTEGER(), nullable=True),
    sa.Column('image_artist', sa.VARCHAR(length=200), nullable=True),
    sa.Column('spotify_url', sa.VARCHAR(length=200), nullable=True)
    )
    op.drop_table('tb_artist')
    # ### end Alembic commands ###
