"""empty message

Revision ID: ccd11dbb69be
Revises: 
Create Date: 2023-11-20 19:18:10.722719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccd11dbb69be'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_followed_artists',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('artist', sa.String(length=50), nullable=True),
    sa.Column('genres', sa.String(length=200), nullable=True),
    sa.Column('popularity', sa.Integer(), nullable=True),
    sa.Column('image_artist', sa.String(length=200), nullable=True),
    sa.Column('spotify_url', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_profile',
    sa.Column('spotify_id', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('profile', sa.String(length=200), nullable=True),
    sa.Column('spotify_profile', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('spotify_id')
    )
    op.create_table('tb_track',
    sa.Column('song_id', sa.String(length=200), nullable=False),
    sa.Column('song', sa.String(length=200), nullable=True),
    sa.Column('artist', sa.String(length=200), nullable=True),
    sa.Column('album', sa.String(length=200), nullable=True),
    sa.Column('release', sa.String(length=200), nullable=True),
    sa.Column('popularity', sa.String(length=200), nullable=True),
    sa.Column('preview_url', sa.String(length=200), nullable=True),
    sa.Column('images_url', sa.String(length=200), nullable=True),
    sa.Column('spotify_song', sa.String(length=200), nullable=True),
    sa.Column('spotify_artist', sa.String(length=200), nullable=True),
    sa.Column('spotify_album', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('song_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_track')
    op.drop_table('tb_profile')
    op.drop_table('tb_followed_artists')
    # ### end Alembic commands ###
